### ISSUE TITLE
 How can I get the vocfsdet_20{07,12}_trainval_{base,all}{1,2,3}

### ISSUE THREAD

**Issue by john2020-210** [Megvii-BaseDetection/GFSD#2]

**Comment by zb1439** [comment]
See https://github.com/Megvii-BaseDetection/GFSD/blob/master/FSDET_DATASET.md

**Comment by 2006pmach** [comment]
Same question here. I checked the file you shared above but I don't get it. There are like a million files at http://dl.yf.io/fs-det/datasets/ and it seems I would even have to rename all of them. Could you please explain a bit more detailed which files I need and what the second paragraph with all the vocfsdet means? What do I need to do with these? Where do I need to put the files in the end in the cvpods/dataset/voc or coco folder or somewhere in this repo?

Otherwise could you please zip the files and share a link or prepare a script that downloads the needed files and that renames them given your format? Thanks in advance.

**Comment by zb1439** [comment]
> Same question here. I checked the file you shared above but I don't get it. There are like a million files at http://dl.yf.io/fs-det/datasets/ and it seems I would even have to rename all of them. Could you please explain a bit more detailed which files I need and what the second paragraph with all the vocfsdet means? What do I need to do with these? Where do I need to put the files in the end in the cvpods/dataset/voc or coco folder or somewhere in this repo?
> 
> Otherwise could you please zip the files and share a link or prepare a script that downloads the needed files and that renames them given your format? Thanks in advance.

Good suggestion! Since I don't have these data on hand now, I will probably work on a script to try to do these jobs. But before that, you can try wget --recursive to get the directories, and actually, you only need to modify the names of the parent folder and the datasplit folder.

**Comment by zb1439** [comment]
> Same question here. I checked the file you shared above but I don't get it. There are like a million files at http://dl.yf.io/fs-det/datasets/ and it seems I would even have to rename all of them. Could you please explain a bit more detailed which files I need and what the second paragraph with all the vocfsdet means? What do I need to do with these? Where do I need to put the files in the end in the cvpods/dataset/voc or coco folder or somewhere in this repo?
> 
> Otherwise could you please zip the files and share a link or prepare a script that downloads the needed files and that renames them given your format? Thanks in advance.

You can see the latest release now. I have attached a zip file there and FSDET_DATASET.md is also updated.

**Comment by 2006pmach** [comment]
Ah great, thanks for sharing the files. I just didn't understand what I have to do with vocfsdet datasets. After checking https://github.com/ucbdrive/few-shot-object-detection/blob/master/datasets/README.md it got more clear.
Maybe you want to add this. Btw. in the zip you shared there are a lot of index.html files (I guess from wget). Maybe you want to delete them. Thanks.
